version: '3.8'
services:
  rabbitmq_ecommerce:
    container_name: rabbitmq_ecommerce
    image: rabbitmq:3.11.14-alpine
    ports:
      - "5672:5672"
    expose:
      - 5672
    restart: on-failure
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - .:/data
    networks:
      - ecommerce_network
    environment:
      RABBITMQ_DEFAULT_USER: EcommerceQ123
      RABBITMQ_DEFAULT_PASS: EcommercePasswordQ1303

  smtp_server:
    container_name: smtp_ecommerce
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MH_HOSTNAME=mailhog.com
  mongodb_ecommerce:
    container_name: mongodb_ecommerce
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo_data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ecommerce0username
      - MONGO_INITDB_ROOT_PASSWORD=ecommerce0password
    networks:
      - ecommerce_network
  mongo_express_ecommerce:
    container_name: mongoexpress_ecommerce
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ecommerce0username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ecommerce0password
      - ME_CONFIG_MONGODB_SERVER=mongodb_ecommerce
    networks:
      - ecommerce_network
volumes:
  mongo_data:
  rabbitmq_data:
networks:
  ecommerce_network:
    driver: bridge
