FROM openjdk:21-ea-26-jdk-oraclelinux8
WORKDIR /etc/ecommerce/server
COPY ./ecommerce/build/libs/ecommerce-0.0.1-SNAPSHOT.jar ecommerce-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "ecommerce-0.0.1-SNAPSHOT.jar" ]
