FROM node:20-alpine3.17 AS client-build
WORKDIR /usr/etc/ecommerce/views/client
COPY ecommerce-views .
ENV REACT_APP_SERVER_ENDPOINT=http://k8s-dev-ecommerc-3c69be3041-1790501493.ap-southeast-4.elb.amazonaws.com:8080
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=client-build /usr/etc/ecommerce/views/client/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT [ "nginx","-g", "daemon off;" ]