apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-ecommerce
  template:
    metadata:
      labels:
        app: mongodb-ecommerce
    spec:
      containers:
      - name: mongodb-ecommerce
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-ecommerce-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-ecommerce-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017