apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: dev
  labels:
    tier: queue
spec:
  type: ClusterIP
  selector:
    name: ecommerce-rabbitmq
    tier: queue
  ports:
    - port: 5672
      targetPort: 5672