apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: ecommerce-react-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ecommerce
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: ecommerce-react
    app.kubernetes.io/tier: frontend