apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: ecommerce-spring-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /ecommerce-api/public/api/healthcheck
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: ecommerce-spring
    app.kubernetes.io/tier: backend